services:
  istsos4-gui:
    container_name: istsos4-gui
    image: ghcr.io/istsos/istsos4/gui:1.2
    restart: always
    ports:
      - 2000:3000
    environment:
      NEXT_PUBLIC_BASE_PATH: ${NEXT_APP_URL}
      NEXT_PUBLIC_ISTSOS4_URL: ${NEXT_PUBLIC_ISTSOS4_URL}
      NEXT_PUBLIC_MAP_CENTER: ${NEXT_PUBLIC_MAP_CENTER}
      NEXT_PUBLIC_MAP_ZOOM: ${NEXT_PUBLIC_MAP_ZOOM}
      NEXT_PUBLIC_MAP_DEFAULT_BASEMAP: ${NEXT_PUBLIC_MAP_DEFAULT_BASEMAP}
    networks:
     - istsos4-network
     
networks:
  istsos4-network:
    external: true
